name: visamate
description: "A Travel Visa Recommendation system powered by AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0  <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics:
  fetch_client: ^1.1.1
  firebase_core_web: ^2.15.0
  firebase_crashlytics: ^3.4.9
  firebase_auth: ^4.19.6
  firebase_database: ^10.2.7  
  redacted: ^1.0.11
  dio: ^5.4.3+1
  im_stepper: ^1.0.1+1
  url_launcher: ^6.1.14
  firebase_auth_web:
  cupertino_icons: ^1.0.8
  cached_network_image_builder: ^0.3.0
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.31.1
  cloud_firestore: ^4.13.6
  location: 
  flutter_map:  
  get: ^4.6.6
  overlay_tooltip: ^0.2.3
  build_runner: any
  build_web_compilers: ^4.0.4
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  provider: ^6.1.1
  flutter_native_splash: ^2.3.9
  edit_calendar_event_view: ^0.3.0+30
  syncfusion_flutter_datepicker: ^25.2.4
  syncfusion_flutter_calendar: ^25.2.4
  mpesadaraja: ^0.1.5
  qr_flutter: ^4.1.0
  phonenumbers: ^1.1.1
  printing: ^5.12.0
  pdf: ^3.10.8
  screenshot: ^3.0.0
  mpesa_flutter_plugin: ^1.6.1
  csc_picker: ^0.2.7
  shared_preferences_riverpod: ^0.3.0
  currency_text_input_formatter: ^2.1.14
  country_currency_pickers: ^3.0.0
  flutter_dotenv: ^5.1.0
  # csv: ^6.0.
  material_floating_search_bar: ^0.3.3
  modal_bottom_sheet: ^3.0.0
  # provider: ^5.0.0
  shared_preferences: ^2.0.5
  rxdart: ^0.27.7
  # intl: ^0.18.1
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.0.0
  package_info: ^2.0.0
  introduction_screen: ^3.1.14
  # flutter_svg: ^0.21.0-nullsafety.0
  http: ^0.13.1
  font_awesome_flutter: ^10.7.0
  # dropdown_search: ^1.0.3
  # url_launcher: ^6.0.12
  flutter_gemini: ^2.0.3
  langchain: ^0.5.0+1
  permission_handler: ^11.3.1
  langchain_openai: ^0.5.0+1
  fancy_password_field: ^2.0.6
  flutter_overboard: ^3.1.3
  firebase_ui_oauth: ^1.5.2
  firebase_ui_oauth_google: ^1.3.2
  google_sign_in_android: 6.1.23  # You can use the latest version
  step_progress_indicator: ^1.0.2
  validation_pro: ^1.1.0
  geolocator: ^12.0.0
  flutter_social_button: ^1.1.4
  latlong2: ^0.9.1
  geocoder_offline_json: ^0.2.2
  flutter_gen: ^5.4.0
  convert_native_img_stream: ^0.0.1
  convert: ^3.1.1
  universal_io: ^2.2.2
  icons_plus: ^5.0.0
  twitter_login: ^4.4.2
  flutter_facebook_auth: ^6.0.4
  google_maps_flutter: ^2.6.1
  syncfusion_flutter_maps: ^25.2.4
  google_generative_ai: ^0.4.0
  gap: ^3.0.1
  dio_http_formatter: ^3.2.1
  excel: ^4.0.2
  flip_card: ^0.7.0

  # package_info: ^2.0.0
  # mpesa_flutter_plugin: ^1.5.0
  # qr_code_scanner: ^1.0.1
  # im_stepper: ^1.0.1+
  
dependency_overrides:
  intl: 0.19.0  # Force using intl version 0.19.
  langchain: ^0.5.0+1
  langchain_openai: ^0.5.0+1
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
flutter_icons:
  image_path:  "assets/app_icon/visamate_logo_icon.png"
  color_dark: "#222048"
  color: "#222048"
  android: "launcher_icon"
  ios: true
flutter_native_splash:
  image:  assets/visamate_splash.png
  color: "#ffffff"
  image_dark:  assets/visamate_splash.png
  color_dark: "#222048"

flutter:

  uses-material-design: true
  assets: 
    - assets/visamate_logo_mark.png
    - assets/visamate_splash.png
    - assets/visa_recommendation.csv
    - assets/flags/
    - assets/Passport.jpg
    - assets/json/
    # - assets/visa_requirements.xlsx
    - assets/images/
    - assets/launcher/
    - assets/app_icon/visamate_logo_icon-1.png
    - assets/app_icon/visamate_logo_icon-2.png
    - assets/app_icon/

  fonts:
    - family: Gilmer
      fonts:
        - asset: fonts/Gilmer-Regular.otf
        - asset: fonts/Gilmer-Medium.otf
        - asset: fonts/Gilmer-Heavy.otf
        - asset: fonts/Gilmer-Bold.otf  