final List<String> visaReasons = [
  'Tourism',
  'Business',
  'Work',
  'Study',
  'Family Visit',
  'Medical Treatment',
  'Conference/Event',
  'Transit',
  'Volunteer',
  'Religious Pilgrimage',
  'Other (Please Specify)', // Add an "Other" option for flexibility
];

List<String> languages = [
  'English',
  'Spanish',
  'Mandarin Chinese',
  'Hindi',
  'Arabic',
  'Portuguese',
  'Bengali',
  'Russian',
  'Japanese',
  'German',
  'French',
  'Korean',
  'Italian',
  'Thai',
  'Vietnamese',
  'Turkish',
  'Polish',
  'Urdu',
  'Malaysian',
  'Persian',
  // Add more languages as needed...
];

final List<String> genderItems = [
  'Male',
  'Female',
];

///
///
///
///
final List<String> userLevel = [
  'Minister',
  'Executive',
  'Zonal Minister',
  'Pastor',
  'Ass.HOD',
  'HOD',
  'Member',
  'College Minister'
];
      Map<String, List<String>> counties = {
  "Nairobi": ["Nairobi", "Westlands", "Embakasi", "Kasarani", "Lang'ata", "Roysambu", "Kibra", "Mathare", "Starehe"],
  "Mombasa": ["Mombasa", "Nyali", "Likoni", "Kisauni", "Mvita", "Changamwe", "Jomvu"],
  "Kisumu": ["Kisumu", "Nyakach", "Nyando", "Muhoroni", "Kisumu East", "Kisumu West"],
  "Nakuru": ["Nakuru", "Naivasha", "Nakuru East", "Nakuru West", "Gilgil", "Rongai", "Subukia", "Kuresoi", "Molo", "Bahati"],
  "Uasin Gishu": ["Eldoret", "Moiben", "Soy", "Turbo", "Ainabkoi", "Kapseret"],
  "Kakamega": ["Kakamega", "Butere", "Lugari", "Malava", "Likuyani", "Matungu", "Navakholo", "Khwisero", "Shinyalu"],
  "Meru": ["Meru", "Igembe", "Tigania", "Imenti North", "Imenti South", "Buuri", "Tharaka Nithi", "Isiolo"],
  "Kisii": ["Kisii", "Gucha", "Mugirango", "Nyamira", "Bomachoge Borabu"],
  "Machakos": ["Machakos", "Kangundo", "Mwala", "Yatta", "Masinga", "Matungulu"],
  "Kiambu": ["Kiambu", "Thika", "Githunguri", "Kiambu Town", "Ruiru", "Limuru", "Juja"],
  "Nyeri": ["Nyeri", "Othaya", "Mathira", "Tetu", "Mukurweini"],
  "Kajiado": ["Kajiado", "Ngong", "Kajiado Central", "Kajiado North", "Kajiado East"],
  "Kilifi": ["Kilifi", "Malindi", "Kaloleni", "Kilifi North", "Kilifi South", "Ganze", "Rabai"],
  "Kisii": ["Kisii", "Nyamira", "Keroka", "Suneka", "Kisii Town", "Nyamira Town"],
  "Kirinyaga": ["Kerugoya", "Sagana", "Kutus", "Kerugoya", "Wanguru"],
  "Kwale": ["Kwale", "Kwale Town", "Kinango", "Matuga", "Msambweni"],
  "Laikipia": ["Nanyuki", "Doldol", "Rumuruti", "Nyahururu", "Kinamba"],
  "Lamu": ["Lamu", "Mpeketoni", "Hindi"],
  "Makueni": ["Makueni", "Wote", "Makindu", "Mtito Andei"],
  "Mandera": ["Mandera", "Mandera Town", "Banisa", "Mandera South"],
  "Marsabit": ["Marsabit", "Marsabit Town", "Moyale", "Laisamis"],
  "Meru": ["Meru", "Maua", "Mikinduri", "Nkubu"],
  "Migori": ["Migori", "Migori Town", "Awendo", "Rongo"],
  "Mombasa": ["Mombasa", "Changamwe", "Jomvu", "Kisauni", "Nyali", "Likoni", "Mvita"],
  "Murang'a": ["Murang'a", "Kangema", "Maragua", "Murang'a South", "Kahuro"],
  "Nairobi": ["Nairobi", "Westlands", "Embakasi", "Kasarani", "Lang'ata", "Roysambu", "Kibra", "Mathare", "Starehe"],
  "Nakuru": ["Nakuru", "Naivasha", "Nakuru East", "Nakuru West", "Gilgil", "Rongai", "Subukia", "Kuresoi", "Molo", "Bahati"],
  "Nandi": ["Kapsabet", "Kapsimotwa", "Chepterwai", "Kabisaga", "Kapchorwa"],
  "Narok": ["Narok", "Narok Town", "Narok South", "Narok North", "Trans Mara West", "Trans Mara East"],
  "Nyamira": ["Nyamira", "Nyamira Town", "Nyamira North", "Nyamira South", "Masaba North", "Masaba South"],
  "Nyandarua": ["Ol Kalou", "Ndaragwa", "Nyandarua", "Engineer", "Mirangine"],
  "Nyeri": ["Nyeri", "Nyeri Town", "Nyeri South", "Tetu", "Mathira"],
  "Samburu": ["Maralal", "Samburu East", "Samburu North", "Samburu West", "Baragoi"],
  "Siaya": ["Siaya", "Siaya Town", "Bondi", "Ugunja"],
  "Taita-Taveta": ["Voi", "Taveta", "Mwatate", "Wundanyi", "Taveta"],
  "Tana River": ["Hola", "Garsen", "Madogo", "Bura"],
  "Tharaka-Nithi": ["Kathwana", "Tharaka", "Maara", "Chogoria"],
  "Trans Nzoia": ["Kitale", "Endebess", "Kwanza", "Saboti", "Kiminini"],
  "Turkana": ["Lodwar", "Kakuma", "Lokichar", "Lokichoggio"],
  "Uasin Gishu": ["Eldoret", "Soy", "Kesses", "Ainabkoi", "Moiben", "Tembelio"],
  "Vihiga": ["Vihiga", "Chavakali", "Emuhaya", "Luanda", "Vihiga", "Sabatia"],
  "Wajir": ["Wajir", "Wajir Town", "Wajir South", "Wajir West", "Wajir East", "Tarbaj"],
  "West Pokot": ["Kapenguria", "Sigor", "Lelan", "Kacheliba", "Pokot North", "Pokot Central"],
  // Add more counties and cities as needed
};
final Map<String, String> countryCodes = {
  "AF": "Afghanistan",
  "AX": "Åland Islands",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia (Plurinational State of)",
  "BQ": "Bonaire, Sint Eustatius and Saba",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cabo Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo (Democratic Republic of the)",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Côte d'Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island and McDonald Islands",
  "VA": "Holy See",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran (Islamic Republic of)",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea (Democratic People's Republic of)",
  "KR": "Korea (Republic of)",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MK": "North Macedonia",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia (Federated States of)",
  "MD": "Moldova (Republic of)",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestine, State of",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin (French part)",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten (Dutch part)",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and the South Sandwich Islands",
  "SS": "South Sudan",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom of Great Britain and Northern Ireland",
  "US": "United States of America",
  "UM": "United States Minor Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela (Bolivarian Republic of)",
  "VN": "Viet Nam",
  "VG": "Virgin Islands (British)",
  "VI": "Virgin Islands (U.S.)",
  "WF": "Wallis and Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
};


final List<String> location = [
  'Head Quaters (HQ)',
  'Baragoi',
  'Bondo',
  'Bungoma',
  'Busia',
  'Butere',
  'Dadaab',
  'Diani',
  'Eldoret',
  'Emali',
  'Embu',
  'Garissa',
  'Gede',
  'Gem',
  'Hola',
  'Homa Bay',
  'Isiolo',
  'Kitui',
  'Kibwezi',
  'Kajiado',
  'Kakamega',
  'Kakuma',
  'Kapenguria',
  'Kericho',
  'Keroka',
  'Kiambu',
  'Kilifi',
  'Kisii',
  'Kisumu',
  'Kitale',
  'Lamu',
  'Langata',
  'Litein',
  'Lodwar',
  'Lokichoggio',
  'Londiani',
  'Loyangalani',
  'Machakos',
  'Makindu',
  'Malindi',
  'Mandera',
  'Maralal',
  'Marsabit',
  'Meru',
  'Mombasa',
  'Moyale',
  'Mtwapa',
  'Mumias',
  'Muranga',
  'Mutomo',
  'Nairobi',
  'Naivasha',
  'Nakuru',
  'Namanga',
  'Nanyuki',
  'Naro Moru',
  'Narok',
  'Nyahururu',
  'Nyeri',
  'Ruiru',
  'Siaya',
  'Shimoni',
  'Takaungu',
  'Thika',
  'Ugunja',
  'Vihiga',
  'Voi',
  'Wajir',
  'Watamu',
  'Webuye',
  'Wote',
  'Wundanyi',
];

///
///
///
final List<String> branch = [
  'HQ-Ongata Rongai',
  'Kitengela',
  'Naivasha',
  'Kware'
];

///
///
///
final List<String> college = ['N/A'];

///
///
///
final List<String> group = ['TGL', 'ARK', 'HFC'];

///
///
///
final List<String> zone = ['KWARE TO OLEKASASI', 'KISERIAN', 'GATAKA'];

///
///
///
///
final List<String> religions = [
  'Christianity',
  'Islam',
  'Hinduism',
  'Buddhism',
  'Sikhism',
  'Judaism',
  'Confucianism',
  'Taoism',
  'Shinto',
  'Indigenous Religions',
  'None',
  // Add more religions as needed
];

final List<String> currency = [
  'Euro (EUR)',
  'US Dollar (USD)',
  'British Pound (GBP)',
  'Japanese Yen (JPY)',
  'Australian Dollar (AUD)',
  'Canadian Dollar (CAD)',
  'Swiss Franc (CHF)',
  'Chinese Yuan Renminbi (CNY)',
  'Singapore Dollar (SGD)',
  'Hong Kong Dollar (HKD)',
  'New Zealand Dollar (NZD)',
  'Mexican Peso (MXN)',
  'Indian Rupee (INR)',
  'Brazilian Real (BRL)',
  'South African Rand (ZAR)',
  'Russian Ruble (RUB)',
  'Thai Baht (THB)',
  'Indonesian Rupiah (IDR)',
  'Korean Won (KRW)',
  'Turkish Lira (TRY)',
];



///
///
///
final List<String> gender = [
  'Male',
  'Female',
  'Rather not say'
];final List<String> serviceType = [
  'Community Meeting',
  'Service',
];
final List<String> childAge = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12'
];
final List<String> months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
final List<String> days = List<String>.generate(31, (index) => (index + 1).toString());

  Map<String, int> daysInMonth = {
    'January': 31,
    'February': 28, // Not accounting for leap years
    'March': 31,
    'April': 30,
    'May': 31,
    'June': 30,
    'July': 31,
    'August': 31,
    'September': 30,
    'October': 31,
    'November': 30,
    'December': 31,
  };

 String selectedMonth = 'January';
  final int currentYear = DateTime.now().year;
final List<String> years = List<int>.generate(18, (index) => currentYear - index)
    .map((year) => (1940 + year).toString())
    .toList();





///
///
///
final List<String> departments = ['Creative Arts', 'Media', 'Praise & Worship'];

///
///
