// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRKCeAj7tVaUKC8s_jAC-JrosDoPLj9w',
    appId: '1:183560475594:web:749b08819fce942f2db533',
    messagingSenderId: '183560475594',
    projectId: 'visamate',
    authDomain: 'visamate-e1631.firebaseapp.com',
    storageBucket: 'visamate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtyo-AfTolvVa34uTmCgCFsPUS2YnxJV0',
    appId: '1:183560475594:android:ea880f160f0c8c582db533',
    messagingSenderId: '183560475594',
    projectId: 'visamate',
    storageBucket: 'visamate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaM_OPm67NwPEM3FLjnMeEdO4McvAqJS4',
    appId: '1:183560475594:ios:49869e92abe20a502db533',
    messagingSenderId: '183560475594',
    projectId: 'visamate',
    storageBucket: 'visamate.appspot.com',
    iosBundleId: 'com.example.visamate',
  );
}
